Flattening  - Extensively used  in  Data Science 



In [4]:
#flatenting makes tha two   arrays  into a  ione  array 
import  numpy as np  

a = np.array([[1,2],[3,4]])
a  = a.ravel() 
a 


array([1, 2, 3, 4])

Transpose   


In [6]:
a =  np.array([[1,2,3]  ,  [4,5,6]])  
a  = a.T
a 


array([[1, 4],
       [2, 5],
       [3, 6]])

Reshaping 

In [9]:
a =  np.array([1 , 2 ,3  ,4 ,5 ,6  , 7  , 8   ])
b  = a.reshape(2  ,4 )
b 


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

NewAxis 



In [11]:
z  =  np.array([1  ,   2  , 3  , 4 , 5  , 6 ,7  ,8  ,9  ,10 ])
z  = z[: , np.newaxis]
z  


array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

Dimentional Reshufling 



In [14]:
a =  np.arange(4  * 3  * 2  ).reshape(4  , 3  ,2 )
print(a.shape)

a 


(4, 3, 2)


array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]],

       [[12, 13],
        [14, 15],
        [16, 17]],

       [[18, 19],
        [20, 21],
        [22, 23]]])

Accessing


In [15]:
a[0 , 2 ,1  ]

5

Resizing 


In [17]:
a =  np.array([1  ,2  , 3 , 4  ])
a.resize((8,  ))
a 


array([1, 2, 3, 4, 0, 0, 0, 0])

Sorting Data  


In [18]:
a  = np.array([[1,2,5,3] , [7,5,3,1]])
a = np.sort( a ,  axis = 1  )
a  


array([[1, 2, 3, 5],
       [1, 3, 5, 7]])

Sorting  with fancy indexing 


In [20]:
a  = np.array([5,4,1,8])
j = np.argsort(a) #the  postion of the  indices afetr sorting  

j  


array([2, 1, 0, 3])